//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduzeniethFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Course_Id { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> teacherID { get; set; }
        public string Course_desc { get; set; }
        public System.DateTime Created_at { get; set; }
    }
}
